print('Bienvenido al encriptador de Erre.')
print()
print('1- Encriptar  2- Desencriptar')
print()
opc = input('Ingresa una opcion: ')
if opc == '1':
    print()
    texto = input('Ingresa el texto que quieres encriptar:\n\n')
    print()
    textoA = texto.replace('a', '8.')
    textoB = textoA.replace('b', '9.')
    textoC = textoB.replace('c', '5.')
    textoD = textoC.replace('d', '2.')
    textoE = textoD.replace('e', '3.')
    textoF = textoE.replace('f', '7.')
    textoG = textoF.replace('g', '1.')
    textoH = textoG.replace('h', '0.')
    textoI = textoH.replace('i', '6.')
    textoJ = textoI.replace('j', '4.')
    textoK = textoJ.replace('k', ',.')
    textoL = textoK.replace('l', '#')
    textoM = textoL.replace('m', '!.')
    textoN = textoM.replace('n', '/.')
    textoO = textoN.replace('o', '(.')
    textoP = textoO.replace('p', '=.')
    textoQ = textoP.replace('q', '&.')
    textoR = textoQ.replace('r', '{.')
    textoS = textoR.replace('s', '~.')
    textoT = textoS.replace('t', '`.')
    textoU = textoT.replace('u', '].')
    textoV = textoU.replace('v', '[.')
    textoW = textoV.replace('w', '*.')
    textoX = textoW.replace('x', '%.')
    textoY = textoX.replace('y', ':.')
    textoZ = textoY.replace('z', '-.')
    final = textoZ.replace(' ', '+.')
    print('Tu texto encriptado esta abajo')
    print()
    print(final)
if opc == '2':
    print()
    texto2 = input('Ingresa el texto que quieres desencriptar:\n\n')
    print()
    textoA = texto2.replace('8.', 'a')
    textoB = textoA.replace('9.', 'b')
    textoC = textoB.replace('5.', 'c')
    textoD = textoC.replace('2.', 'd')
    textoE = textoD.replace('3.', 'e')
    textoF = textoE.replace('7.', 'f')
    textoG = textoF.replace('1.', 'g')
    textoH = textoG.replace('0.', 'h')
    textoI = textoH.replace('6.', 'i')
    textoJ = textoI.replace( '4.', 'j')
    textoK = textoJ.replace(',.', 'k')
    textoL = textoK.replace('#', 'l')
    textoM = textoL.replace('!.', 'm')
    textoN = textoM.replace('/.', 'n')
    textoO = textoN.replace( '(.', 'o')
    textoP = textoO.replace('=.', 'p')
    textoQ = textoP.replace( '&.', 'q')
    textoR = textoQ.replace('{.', 'r')
    textoS = textoR.replace('~.', 's')
    textoT = textoS.replace('`.', 't')
    textoU = textoT.replace( '].', 'u')
    textoV = textoU.replace( '[.', 'v')
    textoW = textoV.replace('*.', 'w')
    textoX = textoW.replace('%.', 'x')
    textoY = textoX.replace(':.', 'y')
    textoZ = textoY.replace('-.', 'z')
    final = textoZ.replace('+.', ' ')
    print('Tu texto desencriptado esta abajo')
    print()
    print(final)
    
